### DISCUSSION TITLE
broker page doesn't show celery information

### DISCUSSION THREAD

**Discussion by avico78** [mher/flower#1106] [Q&A]
I do see the tasks coming and dashboard show all information 
 but broker page show everything as N/A

![image](https://user-images.githubusercontent.com/9049952/118161003-bc408000-b427-11eb-8b3e-d98c8a1d85a0.png)

Running flower on docker:
```
  flower:
    image: mher/flower:latest
    command: ["flower", "--broker=redis://redisjson:6379/0", "--port=5555"]
    ports:
      - 5555:5555
    depends_on:
      - redisjson


```
