### DISCUSSION TITLE
Flower not showing any workers

### DISCUSSION THREAD

**Discussion by dstromberg** [mher/flower#1313] [Q&A]
Hello people.

I'm attempting to set up Flower for use with two Celery Workers, using docker-compose.

Flower responds to web browser requests, but shows no activity from Celery; the Workers and Tasks tabs both show:
Showing 0 to 0 of 0 entries.

I've googled about this for a couple of hours, but I seem to be getting nowhere.

I'm starting Flower with:
```
  flower:
    container_name: flower
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@${RABBIT_HOST}//
      - FLOWER_PORT=5555
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq
```

The CELERY_BROKER_URL looks like:
    amqp://username:password@rabbitmq:5672/tact-dev
...except I've redacted the username and password.

I have two celery workers, one of which is started with:
```
  celery_worker:
    hostname: celery_worker
    build:
      context: ${GAME_PUBLISHING_CODE}/services/api
      dockerfile: ./deploy/celery/celery.Dockerfile
      args:
        ...
    restart: always
    # https://github.com/docker/go-units/blob/f2145db703495b2e525c59662db69a7344b00bb8/ulimit.go#L46-L62
    # https://forums.docker.com/t/docker-compose-yml-ulimits/59330
    ulimits:
      core:
        soft: -1
        hard: -1
    ports:
      - "6000:6000"
    container_name: celery_worker
    environment:
      ...
    volumes:
      ...
    command: /bin/bash -c './scripts/create-permissive-bucket --bucket-name somebucketname --endpoint-url http://s3-server:80/ && /usr/local/bin/tact-python -u -m debugpy --listen 0.0.0.0:5678 -m celery --app=service.run:celery worker --concurrency=8 -E --loglevel=DEBUG -Ofair --logfile=/var/log/celery-worker/celery-worker.log'
    depends_on:
      rabbitmq:
        condition: service_healthy
      s3minio:
        condition: service_started
      splunk:
        condition: service_healthy
    privileged: true
    cap_add:
      - SYS_PTRACE

```
The three "..." are places where I've abbreviated this post in the interest of keeping it shorter.

I only recently set up a result backend in celery, and am not 100% sure it is working yet.  I'm assuming it's needed for Flower?  We have maybe hundreds of tasks right now, but I believe they're all fire and forget.

Where would I find the logs for the flower container?  I've exec'd in, but I don't see them anywhere.  EG:
```
/data $ find / -name '*.log' -print
find: /root: Permission denied
find: /proc/tty/driver: Permission denied
/data $
```

Thanks!
