### ISSUE TITLE
alternate named rabbit queues are not seen by flower

### ISSUE THREAD

**Issue by ajwillo** [mher/flower#1008]
**Describe the bug**
When the default rabbit queues are changed with the below celery config, all of the tabs are empty in flower, when I remove the below config, I can see all the data back in flower whilst its using default queue names. this is using the flower docker container

```
# set app name
app_name = 'my app'
# Optional configuration, see the application user guide.
app.conf.update(
    result_expires=3600,
    control_exchange=app_name,
    event_exchange=app_name + '.ev',
    task_default_queue=app_name,
    task_default_exchange=app_name,
    task_default_routing_key=app_name,
)
```

docker compose:
```
flower:  
    image: mher/flower
    command: flower --broker=amqp://rabbitmq:5672 --basic_auth=admin:passowrd
    ports:  
      - 5555:5555 
    depends_on:
      - rabbitmq
```

**To Reproduce**
1. change queue names in RabbitMQ
2. start flower with "flower --broker=amqp://rabbitmq:5672 --basic_auth=admin:password
3. create a task in celery
4. all tabs are empty

**Expected behavior**
should be able to see the queues in the tabs

**Screenshots**
<img width="1269" alt="Screenshot 2020-07-22 at 15 32 57" src="https://user-images.githubusercontent.com/24481217/88189217-ba0afc00-cc30-11ea-9143-3835eee67dbd.png">

**System information**
~ $ python -c 'from flower.utils import bugreport; print(bugreport())'
flower   -> flower:0.9.2 tornado:5.1.1 babel:2.6.0
software -> celery:4.2.1 (windowlicker) kombu:4.2.2-post1 py:3.7.2
            billiard:3.5.0.5 py-amqp:2.3.2
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled
