### ISSUE TITLE
Flower get permission denied when add "--persistent=True"

### ISSUE THREAD

**Issue by RodrigoBCC** [mher/flower#1019]
Hi, 

I have a docker-compose with django app, 2 workers(under django) and Flower. Flower is ok, but when restart my containers losing data task from flower... I search here for answer and found this flag: "--persistent=True", but when i run i get permission denied. Can anyone help me?

docker-compose:

```
  celery1:
    image: xxxx
    container_name: worker-aws
    command: bash -c " ./wait_db_docker.sh && celery -A litoteca worker -l info -Q aws_queue"
    environment:
      - TRY_LOOP=50
      - NAME=database
      - DB_HOST=database
      - DB_PORT=5432
      - REDIS_HOST=redis
    depends_on:
      - rocklab
    volumes:
      - ../:/usr/src/app
    links:
      - database
      - redis

flower:
    restart: always
    image: mher/flower
    container_name: flower
    command: ["flower", "--broker=redis://:seismic@redis:6379/0", "--basic_auth=petrec:seismic", "--port=5555", "--persistent=True", "--db=/data/flower"] 
    # environment:
    #   - CELERY_BROKER_URL=redis://redis:6379/0
    #   - FLOWER_PORT=5555
    # working_dir: /usr/src/app
    expose:
      - "5555"
    volumes:
      - ../flower_data:/data
      # - ../:/usr/src/app
    links:
      - redis
```

the only way I managed to run it was by placing the flower with the same image as the celery:

```
flower:  
    image :xxx
    command: bash -c "celery flower -A litoteca --broker=redis://:seismic@redis:6379/0 --port=5555 --persistent=True --db=flower"
    container_name: flower
    environment:
      - DB_HOST=database
      - REDIS_HOST=redis
    volumes:
      - ../flower:/usr/src/app/flower
    expose:
      - "5555"
    links:
      - redis
      - databas
```

However, i dont want map my app code to flower...
