### ISSUE TITLE
Flower doesn't write task info into db in persistent mode

### ISSUE THREAD

**Issue by Fan-Gong** [mher/flower#1020]
Hi,

I faced with the issue that the flower state can be reloaded from the db file but flower never writes tasks info into the db file. Here are some descriptions:

flower == 0.9.5
celery == 4.4.2

I started my flower by using this command:
``` 
flower --broker=pyamqp://guest:guest@rabbitmq:5672// --loglevel=INFO --persistent=True --db=/etc/db/flower.db
```
and i have configured my docker-compose yaml as below for my flower image:
```
async-task-flower:
  build:
    context: ./flower
    dockerfile: Dockerfile.flower
  volumes:
    - type: bind
      source: ./flower/storage
      target: /etc/db
  environment:
    - LOG_LEVEL=INFO
    - CELERY_BROKER=pyamqp://guest:guest@rabbitmq:5672//
    - FLOWER_DATABASE=/etc/db/flower.db
```

I have tested that the file /etc/db/flower.db is writable and i can see this log info:
```
[D 200827 17:38:14 events:96] Loading state from '/etc/db/flower.db'...
```
But it never save state when I finish running new tasks.

I have checked one of the answers from stack overflow https://stackoverflow.com/questions/46927668/celery-flower-persistent-data-not-restored. Does that mean my tasks should be registered in flower first and then can be stored? Here is the snapshot for my current flower task view (I believe they are all default celery task):

```
async-task-flower_1         |     Registered tasks:
async-task-flower_1         |     ['celery.accumulate',
async-task-flower_1         |      'celery.backend_cleanup',
async-task-flower_1         |      'celery.chain',
async-task-flower_1         |      'celery.chord',
async-task-flower_1         |      'celery.chord_unlock',
async-task-flower_1         |      'celery.chunks',
async-task-flower_1         |      'celery.group',
async-task-flower_1         |      'celery.map',
async-task-flower_1         |      'celery.starmap']
```

Thank you so much!
