### ISSUE TITLE
RabbitMQ management api can't connect

### ISSUE THREAD

**Issue by gentunian** [mher/flower#1036]
**Describe the bug**

When opening the "broker" tab, nothing is shown.

**To Reproduce**

1. Use this docker-compose.yml:
```
version: '3'

services:

  broker:
    image: rabbitmq:3.8-management

  monitor:
    image: mher/flower:0.9.5
    command:  flower --address=0.0.0.0 --port=5555 --broker=$CELERY_BROKER_URL --broker_api=$CELERY_BROKER_API_URL
    environment:
      CELERY_BROKER_URL: amqp://broker:5672
      CELERY_BROKER_API_URL: http://guest:guest@broker:15672/api
    ports:
      - 5555:5555
```
2. run it: `docker-compose up`
3. Open http:localhost:5555/broker

**Expected behavior**

Flower showing rabbitmq management api connection.

**Actual behavior**

```
broker_1   | {bad_header,<<"GET /api">>}
monitor_1  | [E 201030 16:57:13 broker:84] RabbitMQ management API call failed: [Errno 104] Connection reset by peer
```
