### ISSUE TITLE
Connect to Amazon MQ RabbitMQ

### ISSUE THREAD

**Issue by chris-elgato** [mher/flower#1042]
Hi,

I am trying to connect flower version 0.9.5 from Docker Hub with a RabbitMQ instance launched via AWS MQ (https://aws.amazon.com/about-aws/whats-new/2020/11/announcing-amazon-mq-rabbitmq/).

Unfortunately it is not working. I assume this has to do with the fact, that the RabbitMQ instance from AWS only supports `amqps`. But even with the trick from https://github.com/mher/flower/issues/843, I can't connect to it.

This is my last docker-compose file out of many tries:
```
services:
  flower:
    image: mher/flower:0.9.5
    environment:
      CELERY_BROKER_URL: amqp://rabbitmq:password@123.mq.us-east-1.amazonaws.com:5671/vhost?ssl=true
      FLOWER_DB: /tmp/flowerdb
      FLOWER_PERSISTENT: 'False'
    ports:
     - 5555:5555
    command:
     - flower --broker_api=https://rabbitmq:password@123.mq.us-east-1.amazonaws.com/api/
```
