### ISSUE TITLE
Flower docker container failing to inspect broker and pick up tasks

### ISSUE THREAD

**Issue by tstirrat15** [mher/flower#1049]
**Describe the bug**
```
celmon_1                         | [I 201212 00:16:45 mixins:229] Connected to redis://redis:6379/2
celmon_1                         | [W 201212 00:16:50 control:49] 'stats' inspect method failed
celmon_1                         | [W 201212 00:16:50 control:49] 'active_queues' inspect method failed
celmon_1                         | [W 201212 00:16:50 control:49] 'registered' inspect method failed
celmon_1                         | [W 201212 00:16:50 control:49] 'scheduled' inspect method failed
celmon_1                         | [W 201212 00:16:50 control:49] 'active' inspect method failed
celmon_1                         | [W 201212 00:16:50 control:49] 'reserved' inspect method failed
celmon_1                         | [W 201212 00:16:50 control:49] 'revoked' inspect method failed
celmon_1                         | [W 201212 00:16:50 control:49] 'conf' inspect method failed
```

This happens even after `docker-compose restart flower-container` when the `celery` containers are up and running (i.e. it's not a dupe of the bug about inspecting before celery workers have started).

This also happens after using the `refresh` button on the dashboard interface.

There may be a version mismatch between `celery` and `flower` - could that be a problem?

**To Reproduce**
```yaml
version: '2.1'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  worker:
    image: celery:something # potentially outdated
    environment:
      # Relevant env vars here
    volumes:
      - .:/usr/src/app
  celmon:
    image: mher/flower:0.9.5
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/2
    ports:
      - "5555:5555"
    depends_on:
      redis:
        condition: service_healthy
```

**Expected behavior**
I would expect discovery to happen, even without `flower` being aware of the celery app directly (i.e. `-A myapp`).

Is this what I"m getting wrong? If so, I'm happy to update the docs to that end.

**System information**
```
flower   -> flower:0.9.5 tornado:6.0.4 humanize:2.4.1
software -> celery:4.4.6 (cliffs) kombu:4.6.11 py:3.8.3
            billiard:3.6.3.0 redis:3.5.3
platform -> system:Linux arch:64bit
            kernel version:5.8.0-31-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:disabled
```

**Comment by tstirrat15** [comment]
My issue was that I had specified the backend, not the broker, and had gotten the two confused. I got those straight and flower began picking up tasks as it was supposed to.

**Comment by dkdndes** [comment]
@tstirrat15  any chance you correct the above, I have the same issue and don't see it?

**Comment by tstirrat15** [comment]
@dkdndes it was something to the effect of:

```yaml
version: '2.1'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
   rabbit:
    image: rabbitmq
  worker:
    image: celery:something # potentially outdated
    environment:
      # Relevant env vars here
    volumes:
      - .:/usr/src/app
  celmon:
    image: mher/flower:0.9.5
    environment:
      - CELERY_BACKEND_URL=redis://redis:6379/2
      - CELERY_BROKER_URL=amqp://rabbitmq:rabbitmq@rabbit:5672
    ports:
      - "5555:5555"
    depends_on:
      redis:
        condition: service_healthy
```

Note that the broker is pointed at the thing that actually holds tasks - in this case redis is being used to store task results, not the tasks themselves.
