### ISSUE TITLE
Create a release compatible with Celery 5

### ISSUE THREAD

**Issue by samueldg** [mher/flower#1109]
Now that #1021 has been merged, having a new release would make it easier for people installing from PyPI (as opposed to a specific  GitHub commit)

A couple folks have mentioned their interest in the comments: https://github.com/mher/flower/pull/1021#issuecomment-801945805

**Is your feature request related to a problem? Please describe.**
I'm trying to upgrade to Celery 5 without having to install this package from a GitHub commit.

**Describe the solution you'd like**
A new release (possibly a new major release to indicate it's not backwards-compatible) tagged and uploaded to PyPI.

**Comment by purpleshoelace** [comment]
Godspeed!

**Comment by kfortner** [comment]
I have the same issue. I would like to upgrade to Celery 5, but cannot until Flower supports it.

**Comment by johanvergeer** [comment]
Same here. This is the only thing we're waiting for to upgrade to Python 3.9.

**Comment by Smixi** [comment]
Same for me, meanwhile I locally push the module to my local registry.

**Comment by CelestialGuru** [comment]
Currently have this in my pyproject.toml:
```toml
[tool.poetry.dependecies]
# ...
celery = "^5.1.0"
flower = { git = "https://github.com/mher/flower.git", rev = "7ee34cb5fc039bbeb208a54f113713edbb4809ce" }
```
or in requirements.txt:
```
flower @ git+https://github.com/mher/flower.git@7ee34cb5fc039bbeb208a54f113713edbb4809ce
```
Would be nice to specify `flower` by version and get from pypi instead of repo here. Makes it easier to check compatible versions of packages or whatever.
