### ISSUE TITLE
Unknown task while sending tasks through http post

### ISSUE THREAD

**Issue by vectar31** [mher/flower#1119]
Hey, 

I have a microservices setup written in python and I use redis as a message broker for celery. The only problem I am facing is sending tasks using http requests. I want to use the http api because I want to send tasks through a c++ service.  I run flower as a docker container. Here is the compose file. 

```
flower:
    image: mher/flower:0.9.7
    container_name: flower
    environment:
      - CELERY_BROKER_URL=redis://default:vWH4lyqkfT5LCVGak58Dx3cXlG6lwa6eZ9to0NUcQFa@redis:6379/0
      - FLOWER_PORT=8888
      - FLOWER_DEBUG=true
    ports:
      - 8888:8888
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    networks:
      service_mesh:
```
My containers run on a server at `http://55.225.111.5`
Hitting `http://55.225.111.5:8888/api/task/types`  works fine and returns the list of seen tasks so I know that flower is up and I am able to call flower api. 

But when I try to execute a task using `http://55.225.111.5:8888/api/task/async-apply/live.tasks.update_results_for_live_task`
It returns 404 (Unknown task.) In docker logs also I can see :
```
[W 210624 06:43:29 web:1787] 404 POST /api/task/async-apply/live.tasks.update_results_for_live_task (103.121.115.186): Unknown task 'live.tasks.update_results_for_live_task'
[W 210624 06:43:29 web:2239] 404 POST /api/task/async-apply/live.tasks.update_results_for_live_task (103.121.115.186) 1.09ms
```

I am very new to this so please bear with me. If you need any other information please let me know, I will try to make the issue more clear.
