### ISSUE TITLE
Docker tag "latest" isn't latest

### ISSUE THREAD

**Issue by Hultner** [mher/flower#1126]
## Background
I started getting some problems with flower when I upgraded to Celery 5, had to fiddle around quite a bit until I found this configuration in my docker-compose to work
```yaml
  flower:
    image: mher/flower:latest
    networks:
      - ${PUBLIC_NETWORK?Variable not set}
      - default
    depends_on: 
      - queue
      - pdf-celeryworker
      - celeryworker
    env_file:
      - .env
    command: celery flower
      # The ones below did not work anymore
      # - "--broker=amqp://[REDACTED]:5672//"
      # - "celery --broker=amqp://[REDACTED]:5672// flower"
    environment: 
      CELERY_BROKER_URL: "amqp://[REDACTED]:5672//"
      CELERY_RESULT_BACKEND: "rpc://[REDACTED]//"
    deploy:
      labels:
        [REDACTED]
```

After some more investigation that the `latest`-tag pushed at `"2021-07-07T01:41:23.237381Z"` is actually a previous version, 0.9.5. 

This can be verified by running `flower --version` inside of the container.
```
docker-compose exec flower flower --version
0.9.5
4.4.7 (cliffs)
```

From the releases on GitHub I expected latest to be version 1.0, but no tag at version 1 seem to exists.
