### ISSUE TITLE
Flower show wrong time if timezone set

### ISSUE THREAD

**Issue by PaleNeutron** [mher/flower#1132]
**Describe the bug**
My local time is UTC+8, but I can not got correct local time in flower view.

My docker settings:

```
  flower:
    image: mher/flower
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - CELERY_TIMEZONE=Asia/Shanghai
      - CELERY_ENABLE_UTC=True
```
and the same in worker docker.

task request at local time `21:00` shown `05:00` in flower. it has a 2 * 8 hours different.

at this time, I checked task info in redis and got:
```
In [9]: datetime.utcfromtimestamp(1627824019.4668603)
Out[9]: datetime.datetime(2021, 8, 1, 13, 20, 19, 466860)
```
which is correct, UTC+8 's 21:00 is UTC 's 13:00.

so why when flower show a utc time in UTC+8 not plus 8 but minus？

**To Reproduce**
set both worker and flower with `CELERY_TIMEZONE`, request a task, and got wrong time show in flower.

**Expected behavior**
right time.

**System information**
Output of `python -c 'from flower.utils import bugreport; print(bugreport())'` command

```
flower   -> flower:1.0.0 tornado:6.1 humanize:3.10.0
software -> celery:5.1.2 (sun-harmonics) kombu:5.1.0 py:3.9.6
            billiard:3.6.4.0 py-amqp:5.0.6
platform -> system:Linux arch:64bit
            kernel version:5.4.0-80-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

deprecated_settings: None
```

**Comment by felixriese** [comment]
I have the same issue. It seems like this could have been resolved by #1162 and is just not released yet (fix from November '21, release from July '21). Did you check this already?

**Comment by felixriese** [comment]
Update: With `1.0.0`, I am pretty sure this worked for me:

```yaml
  flower:
    image: mher/flower:1.2.0
    command: celery flower
    ports:
      - 5000:5000
    environment:
      - CELERY_TIMEZONE=Europe/Berlin
      - CELERY_ENABLE_UTC=True
      - TZ=Europe/Berlin
```

Now with `1.2.0`, it doesn't anymore. Any ideas what else to try?
