### ISSUE TITLE
Persistence not working with docker compose ?

### ISSUE THREAD

**Issue by CartierPierre** [mher/flower#1145]
Hi,
Here is my docker-compose conf using flower + celery + flask.
Do I have to use a db container too ?
```
version: "3.8"
services:
  flask:
    build: .
    volumes:
      - ./src:/src
      - ./workspace:/workspace
    ports:
      - "80:5000"
    env_file: .env
    command: XXX

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A app.celery worker --concurrency=1 -l INFO --beat -l INFO
    volumes:
      - ./src:/src
      - ./workspace:/workspace
    env_file: .env
    depends_on:
      - flask
      - redis
    
  flower:  
    image: mher/flower
    restart: always
    command: celery flower --persistent=True
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:  
      - 8888:8888
    depends_on:
      - redis
      - celery
```
Each time I do an up and down or just a restart of flower container, all datas are removed.

**Comment by CartierPierre** [comment]
I've got more information. I found some limitations here : https://github.com/mher/flower/issues/662
But it doesn't solve the dashboard problem.
If I look in the task page, I can see `Showing 1 to 10 of 10,042 entries` at the bottom
But in the dashboard I see `Active: 0 Processed: 42 Failed: 0 Succeeded: 42 Retried: 0 ` So the docker restart cleans the dashboard statistics.

**Comment by ENG-Jole** [comment]
When you are recreating the containers you are also recreating the file system that Flower saves the object persistence db to. Flower will persist if the process is restarted on the same file system, but obviously won't persist if a container file system gets recreated, thereby wiping it. You'll need to mount or store the persistence object outside of the container file system if you want it to persist across container restarts.

**Comment by CartierPierre** [comment]
Hi @ENG-Jole , I've used persistance and volume (in the second message), I added like this :
```
  flower:  
    image: mher/flower
    restart: always
    command: celery flower --persistent=True
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:  
      - 8888:8888
    depends_on:
      - redis
      - celery
    volumes:
      - flower_data:/data
volumes:
  flower_data:
```
I can see all process in the tasks page, but not in the dashboard after restart. (Maybe I missed something in your comment)
