### ISSUE TITLE
How to correctly inject config?

### ISSUE THREAD

**Issue by ntarocco** [mher/flower#1330]
I am experiencing an issue with `untrusted content`. We are using `msgpack` for serialization.

I deployed `flower` in a separate **standalone** container in our Kubernetes infrastructure, using the image on Docker Hub `mher/flower:2.0`.

Command:
```
command:
              [
                "celery",
                "--config=/var/celery/celeryconfig.py",
                "--broker=amqp://<username>:<password>@mq:5672/",
                "flower",
                "--broker_api=http://<username>:<password>@mq:15672/api/",
                "--basic_auth=<basic-auth>",
                "--conf=/var/flower/flowerconfig.py"
              ]
```

Given the error, I have tried injecting config in various different combinations of this (only one, both, uppercase, prefixed...):

```
celeryconfig.py: |-
    # looks like not really working
    accept_content = ["json", "msgpack", "yaml"]
    task_serializer = "msgpack"
    result_serializer = "msgpack
```

```
flowerconfig.py: |-
    # looks like not really working
    accept_content = ["json", "msgpack", "yaml"]
    task_serializer = "msgpack"
    result_serializer = "msgpack"
```

The error is always the same:

```
return self.channels[channel_id].dispatch_method(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/amqp/abstract_channel.py", line 156, in dispatch_method
listener(*args)
File "/usr/local/lib/python3.11/site-packages/amqp/channel.py", line 1629, in _on_basic_deliver
fun(msg)
File "/usr/local/lib/python3.11/site-packages/kombu/messaging.py", line 650, in _receive_callback
decoded = None if on_m else message.decode()
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/kombu/message.py", line 201, in decode
self._decoded_cache = self._decode()
^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/kombu/message.py", line 205, in _decode
return loads(self.body, self.content_type,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/kombu/serialization.py", line 255, in loads
raise self._for_untrusted_content(content_type, 'untrusted')
kombu.exceptions.ContentDisallowed: Refusing to deserialize untrusted content of type msgpack (application/x-msgpack)
```

Am I injecting config in the wrong way?

**Comment by Andrew-Cha** [comment]
Hi, I am also not able to monitor my workers (the error above is identical).

In docker container "My Celery Worker" the celery workers are configured to serialize over `pickle`.
In another docker container "My Flower Monitoring" the celery flower lives (using the official image).

I am unable to match the config of "My Celery Worker" and "My Flower Monitoring" Celery applications. 

What is the accepted solution to configure Flower's Celery instance in the official image?

**Comment by eexwhyzee** [comment]
so i ran into the same issue with the untrusted content errors today and was able to figure out how to inject the celery config correctly, the `--config` arg for the celery CLI is actually expecting a python-import-style module for the config and not a file path. 

I have a similar setup as @ntarocco with k8s and what you want to do is mount the config map with your celery configuration at the path of the docker container where celery/flower is being invoked, and then pass just the file name (without the `.py` extension) to the `--config` arg. 

Here's my k8s deployment/configmap specs from my working setup for reference:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: celery-config
data:
  celeryconfig.py: |
    accept_content = ['application/x-python-serialize', 'application/json']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flower
  name: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
      - name: flower
        image: mher/flower:2.0.1
        command:
        - "celery"
        args:
        - "--config=celeryconfig"
        - "flower"
        env:
        - name: CELERY_BROKER_URL
          value: <your_broker_url>
        ports:
        - containerPort: 5555
          protocol: TCP
        volumeMounts:
        - mountPath: /data # path where celery/flower is being invoked in the docker container
          name: flower-config
      volumes:
      - configMap:
          name: flower-config
        name: flower-config
```
