### ISSUE TITLE
amqps:// scheme in Broker URL breaks Broker Tab

### ISSUE THREAD

**Issue by DrMeers** [mher/flower#1369]
Running flower via `celery --broker=amqps://...` (as provided by [CloudAMQP plugin on Heroku](https://elements.heroku.com/addons/cloudamqp), for example) means when you check the Broker tab in the Flower dashboard you just see the error message `'amqp' broker is not supported` which is confusing to say the least:

<img width="475" alt="Screenshot 2024-04-12 at 20 45 28" src="https://github.com/mher/flower/assets/48157/390d1509-5f5f-48d1-8125-32797a185d77">

It seems that simply adding a check for `amqps` in `utils/broker.py` would allow this to work correctly; currently it raises `NotImplementedError`

```
if scheme == 'amqp':
    return RabbitMQ(broker_url, *args, **kwargs)
elif scheme == 'redis':
    return Redis(broker_url, *args, **kwargs)
elif scheme == 'rediss':
    return RedisSsl(broker_url, *args, **kwargs)
elif scheme == 'redis+socket':
    return RedisSocket(broker_url, *args, **kwargs)
elif scheme == 'sentinel':
    return RedisSentinel(broker_url, *args, **kwargs)
else:
    raise NotImplementedError
```

As far as I can see, the same `RabbitMQ` class should suffice and already seems to support `https`?

**Comment by 7C-habib** [comment]
@DrMeers any update as to when this will be merged in master.

**Comment by EwertonDCSilv** [comment]
@mher alguma novidade sobre o tema ?

**Comment by EwertonDCSilv** [comment]
Segue o `docker-compose.yaml` que defini:

``` yaml
  celery_flower:
    container_name: "celery_flower"
    environment:
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=amqps://guest:guest@rabbitmq:5672/vhost
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - FLOWER_PORT=8888
    image: mher/flower:latest
    volumes:
      - .:/app
    command: celery flower --port=8888
    ports:
      - 8888:8888
```
