### ISSUE TITLE
FLower image hosted by docker outputs error 'failed to create shim task'

### ISSUE THREAD

**Issue by brunolnetto** [mher/flower#1387]
**Describe the bug**

I use this repository content as reference for flower hosting. Since I am new to the tool, I wrote docker-compose file below to host on my machine:

```
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  flower:
      image: mher/flower:latest
      command: ['flower', '--broker=redis://redis:6379', '--port=5555']
      ports:
        - "5555:5555"
      depends_on:
        - redis
```

I got following error: `Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "flower": executable file not found in $PATH: unknown`

**To Reproduce**

1. Go to repository `https://github.com/brunolnetto/flower-strauss/blob/main/docker-compose.yaml` and clone it OR create a file docker-compose.yaml with above content;
2. Host with Docker Desktop for linux users OR run command `docker compose up --build -d` on linux terminal;
3. See above reported message; 

**Expected behavior**
I expected to host flower monitoring without hassle.

**System information**

```
flower   -> flower:2.0.1 tornado:6.4.1 humanize:4.10.0
software -> celery:5.4.0 (opalescent) kombu:5.3.7 py:3.10.14
            billiard:4.2.0 py-amqp:5.2.0
platform -> system:Linux arch:64bit, ELF
            kernel version:5.15.0-107-generic imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:disabled

deprecated_settings: None
```
