### ISSUE TITLE
Flower can`t monitor the celery workers in Docker ?

### ISSUE THREAD

**Issue by hushaoqing** [mher/flower#761]
This is my docker-compose.yml:
```
my-redis:
  image: redis:alpine
  ports:
    - "6379:6379"
celery-worker:
  image: celery:latest
  links:
    - my-redis:redis
  environment:
    - CELERY_BROKER_URL=redis://redis
  volumes:
    - ~/tmp/celery-worker.py:/data/celery-worker.py
  working_dir: /data
  command: celery -A celery-worker worker -l info -n worker%n
celery-flower:
  image: mher/flower
  ports:
    - "5555:5555"
  volumes:
    - ~/tmp/celery-worker.py:/data/celery-worker.py
  links:
    - my-redis:redis
  working_dir: /data
  command: celery flower --broker=redis://redis --debug
```
