### ISSUE TITLE
'active_queues' inspect method failed

### ISSUE THREAD

**Issue by behconsci** [mher/flower#775]
Hi, I know this is reported multiple times and it was almost always the workers not being responding. but in my case, workers are responding with pong OK if I do: 

    celery -A myproj inspect ping

I get

    -> worker@ip-172-31-38-146: OK
         pong

but in the status of flower, I have these: 

```
Connected to amqp://rqu:**@ec2-18-196-48-27.eu-centra
'stats' inspect method failed
'active_queues' inspect method failed
'registered' inspect method failed
'scheduled' inspect method failed
'active' inspect method failed
'reserved' inspect method failed
'revoked' inspect method failed
'conf' inspect method failed
```

I increased the `inspect_timeout` to 20000. 

what can be wrong? flower can connect to rabbitmq, otherwise I could not have seen the flower page. 

here is rabbitmq management tool page: 

![image](https://user-images.githubusercontent.com/10358323/35435720-0cc4bc2c-028c-11e8-9f44-07e5f8eefa56.png)

what am I doing wrong? 

this is my systemd service part: 

     ExecStart=/bin/sh -c '${FLOWER_BIN} -A ${CELERY_APP} --broker=amqp://${RQUSER}:${RQPWD}@${RQHOST}:5672// --broker_api=http://guest:guest@${RQHOST}:15672/api/'

**NOTE: flower and celery is running in one ec2 server. rabbitmq is running in different server.**

**Comment by adampl** [comment]
Your broker API URL has default username and password, while broker URL has some variables in it. 
Replace "guest" with proper variables and check again.

**Comment by behconsci** [comment]
I changed it now. but still the same problem :/

**Comment by adampl** [comment]
Do all workers, flower and rabbitmq have synchronized clocks and the same timezone?
I mean operating system and Django config.

**Comment by ddavtian** [comment]
I am seeing the same issue using Redis as the broker

```
octo-engine     | [W 180528 00:57:47 control:44] 'stats' inspect method failed
octo-engine     | [W 180528 00:57:47 control:44] 'active_queues' inspect method failed
octo-engine     | [W 180528 00:57:47 control:44] 'registered' inspect method failed
octo-engine     | [W 180528 00:57:47 control:44] 'scheduled' inspect method failed
```

I am starting Flower as follows ..

`flower -A celery_worker --port=${FLOWER_SERVER_PORT} --inspect-timeout=20000 --broker=redis://:${REDIS_PASSWORD}@${REDIS_URL}:${REDIS_PORT}/0 --broker_api=redis://:${REDIS_PASSWORD}@${REDIS_URL}:${REDIS_PORT}/0"`

```
flower                   0.9.2
redis                    2.10.6
celery                   4.1.1
```

```
bash-4.3# celery -A celery_worker inspect ping
2018-05-28 01:01:36,634 config                    line: 169  DEBUG    Loading dev environment
2018-05-28 01:01:37,209 database                  line: 27   INFO     Not Using SSL Connection to mySQL DB
2018-05-28 01:01:37,404 job_scheduler             line: 16   INFO     Initialized JobScheduler
-> celery@e466953bdd44: OK
        pong
```

**Comment by GomezCory** [comment]
Getting a similar issue would love to see if anyone has resolved this yet.

**Comment by stojan-jovic** [comment]
Same problem here, using:
```
billiard (3.5.0.3)
celery (4.1.0)
flower (0.9.2)
kombu (4.1.0)
redis (2.10.6)
tornado (4.5.3)
```

**Comment by Ammadkhalid** [comment]
anyone? same issue here:
```
celery-flower_1  | [W 191001 22:57:35 control:44] 'stats' inspect method failed
celery-flower_1  | [W 191001 22:57:35 control:44] 'active_queues' inspect method failed
celery-flower_1  | [W 191001 22:57:35 control:44] 'registered' inspect method failed
celery-flower_1  | [W 191001 22:57:35 control:44] 'scheduled' inspect method failed
celery-flower_1  | [W 191001 22:57:35 control:44] 'active' inspect method failed
celery-flower_1  | [W 191001 22:57:35 control:44] 'reserved' inspect method failed
celery-flower_1  | [W 191001 22:57:35 control:44] 'revoked' inspect method failed
celery-flower_1  | [W 191001 22:57:35 control:44] 'conf' inspect method failed
```

my docker yml:
```
version: '3'

services:
  my-redis:
    image: redis
    expose:
      - 6379

  celery-worker:
    build: .
    links:
      - my-redis:redis
    ports:
      - "5554:5554"
    command: celery -A src worker -b=redis://redis -l info -n worker-%n

  celery-flower:
    build: .
    ports:
      - "5555:5555"
    links:
      - my-redis:redis
    command: celery -A src flower --loglevel=info --broker=redis://redis
```

**Comment by imomaliev** [comment]
The issue here that worker is not started yet. You need to wait until worker is ready until starting flower https://stackoverflow.com/questions/39107835/flower-doesnt-display-all-workers-for-celery/54570067#54570067

**Comment by odigity** [comment]
I'm glad there's a SO answer explaining the problem and how to solve it when running flower yourself.  However, I'm using the `mher/flower` Docker image.  The stanza in my `docker-compose.yml` file is as follows:

    flower:
      <<: *restart_policy
      image: "mher/flower"
      environment:
      CELERY_BROKER_URL: redis://redis:6379
      depends_on:
        - celery
      ports:
        - "5555:5555"

So, is there a way to incorporate the `inspect ping` step into this scenario?

**Comment by mathbr10** [comment]
@imomaliev 
I am trying to follow your suggestion. But the it seems that celery fowler is waiting forever in my docker compose. But if I try to enter inside the container, and run the command bellow, it returns **pong** to me as expected.

`until timeout  10s celery -A project inspect ping; do`

**Comment by imomaliev** [comment]
@mathbr10 Can you provide your `Dockerfile`, `entrypoint.sh` and `docker-compose.yml` files?

**Comment by mathbr10** [comment]
@imomaliev I am sharing the relevant lines because I cannot share the hole scope, but I think it shows What I did.

docker-compose.yaml
```
  celery_worker:
    build: ./
    restart: always
    # command: celery -A src.app.celery worker --loglevel=info -Q schedule_train,schedule_deploy
    entrypoint: ["celery","-A","src.app.celery", "worker", "--loglevel=info", "-Q", "schedule_train,schedule_deploy"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - src:/ai_engine/src
    environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
        - C_FORCE_ROOT="true"
    depends_on:
      - redis
      - fastapi_app
    networks:
      - my-networks

  dashboard:
      build: ./
      # command: celery -A src.app.celery flower --port=5555
      # entrypoint: ["celery", "-A" ,"src.app.celery", "--broker=redis://redis:6379/0", "flower", "--port=5555"]
      entrypoint:
        - /bin/sh
        - start_flower.sh
      ports:
        - 5556:5555
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
        # - CELERY_BROKER_URL=amqp://admin:mypass@rabbitmq:5672//
        # - CELERY_RESULT_BACKEND=rpc://
      depends_on:
        - celery_worker
        - redis
        - fastapi_app
      networks:
        - my-networks
```

dockerfile (relevant lines)
```
COPY ./start_flower.sh /ai_engine/start_flower.sh
# COPY ./tests /ai_engine/tests

EXPOSE 8000
ENTRYPOINT ["uvicorn", "src.app:fastapi_app", "--host", "0.0.0.0", "--port", "8000"]
```

start_flower.sh
```
#!/bin/sh

until timeout 5s celery -A src.app.celery inspect ping; do
    >&2 echo "Celery workers not available"
done

echo 'Starting flower'
celery -A src.app.celery flower --port=5555 --broker=redis://redis:6379/0
# "celery", "-A" ,"src.app.celery", "flower", "--port=5555", "--broker=redis://redis:6379/0"

```
