### ISSUE TITLE
在docker下使用flower，用github认证，出现access_token获取不到错误

### ISSUE THREAD

**Issue by NullYing** [mher/flower#816]
在docker下使用flower，用github认证，出现以下报错
```python
flower_worker    | [E 180619 06:17:03 web:1621] Uncaught exception GET /login?code=8f98120c1e963bd4267b (172.17.0.12)
flower_worker    |     HTTPServerRequest(protocol='http', host='xxx', method='GET', uri='/login?code=xxxx', version='HTTP/1.1', remote_ip='172.17.0.12')
flower_worker    |     Traceback (most recent call last):
flower_worker    |       File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1499, in _stack_context_handle_exception
flower_worker    |         raise_exc_info((type, value, traceback))
flower_worker    |       File "<string>", line 4, in raise_exc_info
flower_worker    |       File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1700, in wrapper
flower_worker    |         result = method(self, *args, **kwargs)
flower_worker    |       File "/usr/local/lib/python3.6/site-packages/flower/views/auth.py", line 133, in _on_auth
flower_worker    |         access_token = user['access_token']
flower_worker    |     KeyError: 'access_token'
```

**Comment by NullYing** [comment]
docker-compose

```
version: "3"
services:
  flower_worker:
    container_name: flower_worker
    image: mher/flower
    environment:
     - FLOWER_OAUTH2_KEY=*****************
     - FLOWER_OAUTH2_SECRET=*****************
     - FLOWER_OAUTH2_REDIRECT_URI=https://*****************/login
    command: flower --broker=redis://:@redis_url:6379/0 --auth="*****************" --natural_time --auth_provider=flower.views.auth.GithubLoginHandler
    ports:
      - "5555:5555"
    network_mode: bridge
    external_links:
      - "redis:redis_url"
```
