### ISSUE TITLE
Failed to capture events: '[Errno 111] Connection refused' with rabbitmq and docker-compose 

### ISSUE THREAD

**Issue by mattharrigan** [mher/flower#862]
Hello,

I am new to docker.  I am trying to start flower and rabbitmq using docker-compose, yml file below.  However I am getting an error from flower:

> Failed to capture events: '[Errno 111] Connection refused'

What should the docker-compose yml file contain to start a basic stack?  Also I think something like this would be great to add to the docs or examples.

Thank you

```
version: "3"

services:

    rabbitmq:
        image: "rabbitmq:3.6"
        ports:
            - "5672:5672"
    
    flower:
        image: "mher/flower:0.9"
        environment:
            - "CELERY_BROKER_URL=amqp://guest:guest@localhost:5672//"
        ports:
            - "5555:5555"
```
