### ISSUE TITLE
API 50x errors while accessing /api/task/result and /api/task/info

### ISSUE THREAD

**Issue by benjaminh** [mher/flower#978]
I have a flower service running through docker-compose along with a django service.

Flower runs quite fine (except for some issues in the broker and monitor tabs that display nothing) but I have some issues using the API:

- GET `/api/tasks` returns the list of tasks
- GET `/api/task/result/<task_id>` returns a 503 service unavailable error
- GET `/api/task/result/<task_id>` returns a 500 server error : `TypeError: Object of type Task is not JSON serializable`

I've seen some similar issues that appear to be fixed, but I did try to update my docker image and it tells me I have the latest one.

My flower service is declared in my docker-compose file as follows:
```
  flower:
    image: mher/flower
    command: ["flower", "--broker=redis://redis:6379", "--broker_api=redis://redis:6379"]
    ports:  
      - 5555:5555
    depends_on: 
      - redis
    volumes:
      - redis_data:/data:rw
```

**Comment by rappertomate** [comment]
Same problem here. I have Celery and Flower up and running. Rabbit as broker, Redis as backend.  

The Flower dashboard works correctly as far i can tell. Through the API i can submit tasks via `POST /api/task/send-task/my_queue.my_task`. However i can't retrieve them via `GET /api/task/result/<task_id>`. I always receive a `503 Service Unavailable` status.

The [docs](https://flower.readthedocs.io/en/latest/api.html#get--api-task-result-(.+)) suggest that 503 implies not configured backend, however i inspected the Redis instance and i can ensure that the results are stored there.

Excerpt from my docker-compose:

```
version: "3.6"

services:
  rabbit:
    image: rabbitmq:3.8
    container_name: celery_rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=rabbituser
      - RABBITMQ_DEFAULT_PASS=rabbitpassword
    ports:
      - 5672:5672

  redis:
    image: bitnami/redis:5.0.9
    container_name: celery_redis
    environment:
      - REDIS_PASSWORD=redispassword
    ports:
      - 6379:6379

  worker:
    build: .
    depends_on:
      - rabbit
    volumes:
      - ./:/src

  flower:
    image: mher/flower:latest
    container_name: celery_flower
    environment:
        - CELERY_BROKER_URL=amqp://rabbituser:rabbitpassword@rabbit:5672
    ports:
      - 5555:5555
    depends_on:
      - worker
```

**Comment by benjaminh** [comment]
@rappertomate fyi, I used the workaround mentioned in #980 to solve this issue. This does look like a problem due to the docker image being outdated indeed.

I only added a pip command (to install future module) within the original Dockerfile as follows:
```
FROM python:alpine

# Get latest root certificates
RUN apk add --no-cache ca-certificates && update-ca-certificates

# Install the required packages
RUN pip install --no-cache-dir redis flower
RUN pip install future

# PYTHONUNBUFFERED: Force stdin, stdout and stderr to be totally unbuffered. (equivalent to `python -u`)
# PYTHONHASHSEED: Enable hash randomization (equivalent to `python -R`)
# PYTHONDONTWRITEBYTECODE: Do not write byte files to disk, since we maintain it as readonly. (equivalent to `python -B`)
ENV PYTHONUNBUFFERED=1 PYTHONHASHSEED=random PYTHONDONTWRITEBYTECODE=1

# Default port
EXPOSE 5555

# Run as a non-root user by default, run as user with least privileges.
USER nobody

ENTRYPOINT ["flower"]
```
Then, in my docker-compose, I use the Dockerfile instead of the docker image from the official repo.

```
  flower:
    build:
      context: .
      dockerfile: ./docker/flower/Dockerfile
    command: ["flower", "--broker=redis://redis:6379", "--broker_api=redis://redis:6379"]
    ports:  
      - 5555:5555
    depends_on: 
      - redis
```

Hope this helps !
